## Why Numpy?

### 连续存储

### Vectorization

In [3]:
import numpy as np
import time

# 创建一个包含 100 万个数字的数据
data_list = list(range(1000000))
data_arr = np.array(data_list)

# --- 方式 A: Python List (慢) ---
# 你必须写循环，逐个处理
t1 = time.time()
new_list = [x * 2 for x in data_list] 
print(f"Python List 耗时: {time.time() - t1:.5f} 秒")

# --- 方式 B: NumPy (快) ---
# 只要写 arr * 2，它会自动应用到所有元素
t2 = time.time()
new_arr = data_arr * 2 
print(f"NumPy Array 耗时: {time.time() - t2:.5f} 秒")

Python List 耗时: 0.49309 秒
NumPy Array 耗时: 0.01137 秒


In [ ]:
import numpy as np

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

# Example usage:
arr = np.array([3, 6, 8, 10, 1, 2, 15])
print("Original array:", arr.tolist())
sorted_arr = quick_sort(arr)
print("Sorted array:", sorted_arr.tolist())

In [ ]:
print("Hello Vance!")

In [2]:
%%ai ollama:qwen2.5-coder:7b
# 请帮我写一个 Python 函数，实现快速排序算法

UsageError: Cell magic `%%ai` not found.


In [3]:
import numpy as np

In [4]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
print(arr2.shape)
type(arr2)

(2, 5)


numpy.ndarray

numpy.ndarray

In [14]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [17]:
print(arr3[1:2])

[[[ 7  8  9]
  [10 11 12]]]


In [18]:
print(arr3[1,1:2])

[[10 11 12]]


In [20]:
arr4 = np.array(['apples','banana','cherry'])

In [22]:
print(arr4.dtype)

<U6


In [23]:
arr4_=arr4.copy()
print(arr4_.dtype)

<U6


In [27]:
arr = np.array([1,0,-1,4,5])
newarr = arr.astype(bool)

print(newarr)

[ True False  True  True  True]


In [29]:
x = np.random.normal(10)
print(x)

10.844828807577711


In [33]:
y = np.random.normal(170,10,20)
print(y)

[165.82572942 162.79193287 159.92619733 161.99455254 149.94331213
 187.69478015 166.78088511 161.64856306 163.86905486 166.75913182
 164.1334291  171.39722862 169.50582189 157.38326895 181.09742528
 170.24246608 157.90569282 183.86888104 180.09834007 164.92015938]


In [35]:

print("原始数据：")
print(y)

# 标准化：z = (x - mean) / std
y_std = (y - np.mean(y)) / np.std(y)
print("\n标准化后的数据：")
print(y_std)

原始数据：
[165.15576009 183.72903412 177.73551762 177.50766433 153.33441376
 164.44402561 174.53664993 163.15630583 150.66126008 181.57404197
 173.90596476 179.13340091 184.93621238 163.7233453  163.8530453
 167.65888376 172.70082527 180.23825108 160.62119998 170.96282415]

标准化后的数据：
[-0.55904597  1.39172529  0.7622197   0.73828802 -1.80065489 -0.63380022
  0.42623913 -0.76905084 -2.08141914  1.16538411  0.35999758  0.90904091
  1.51851654 -0.70949406 -0.69587153 -0.29614016  0.23342047  1.02508453
 -1.03531578  0.05087631]


In [36]:
import numpy as np

# Define matrix A and vector B
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])

# Solve the system of linear equations Ax = B
x = np.linalg.solve(A, B)
print("Solution to Ax = B:", x)

Solution to Ax = B: [2. 3.]
